languageCode = 'en-us'
title = 'Your Technologist Coach'
theme = 'coaching'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true
